# Generated by Django 4.2 on 2023-06-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('culture', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
